/*Name: Asia Minor
 *Date: 11-29-18
 *Purpose: Write a rainfall class that  stores the total rainfall for each of 12 months into an array of doubles. 
 *Include methods that find the total amount of rain, the average amount of rain, which month had the most rain, and which month had the least rain 
 */

import javax.swing.JOptionPane;
import java.lang.Math;
public class Rainfall {
	
	private static double rainfallInMonths[] = new double[12];
	private static String monthNames[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};;
	
	public static void main(String [] args) {
		
		double max = 75.0, min = 0.0;
		double range = max - min + 1; //sets up the range for the amount of rainfall
		
		for(int i = 0; i < 12; ++i) {
			double doubNum = (double)(Math.random() * range) + min; 
			double newNum = doubNum * 100;
			newNum = Math.round(newNum);
			newNum = newNum / 100;
			rainfallInMonths[i] = newNum; //This segment takes the double and rounds it to 2 decimal places because the original numbers were too big for me
			System.out.println(rainfallInMonths[i]);
		}
		JOptionPane.showMessageDialog(null, "You are going to see the amount of inches it rained each month this year.");
		JOptionPane.showMessageDialog(null, "Rainfall in " + monthNames[0] + ": " + rainfallInMonths[0] + "inches." +
				"\nRainfall in " + monthNames[1] + ": " + rainfallInMonths[1] + " inches." +
				"\nRainfall in " + monthNames[2] + ": " + rainfallInMonths[2] + " inches." +
				"\nRainfall in " + monthNames[3] + ": " + rainfallInMonths[3] + " inches." +
				"\nRainfall in " + monthNames[4] + ": " + rainfallInMonths[4] + " inches." +
				"\nRainfall in " + monthNames[5] + ": " + rainfallInMonths[5] + " inches." +
				"\nRainfall in " + monthNames[6] + ": " + rainfallInMonths[6] + " inches." +
				"\nRainfall in " + monthNames[7] + ": " + rainfallInMonths[7] + " inches." +
				"\nRainfall in " + monthNames[8] + ": " + rainfallInMonths[8] + " inches." +
				"\nRainfall in " + monthNames[9] + ": " + rainfallInMonths[9] + " inches." +
				"\nRainfall in " + monthNames[10] + ": " + rainfallInMonths[10] + " inches." +
				"\nRainfall in " + monthNames[11] + ": " + rainfallInMonths[11] + " inches.");
		
		double t = Total(rainfallInMonths); //t stands for total
		Average(t);
		Highest(rainfallInMonths, monthNames);
		Lowest(rainfallInMonths, monthNames);
	}
	//Takes the total of the values in the array
	//@param array[], the array generated by the math class
	//@return total, returns the total of the rainfall in the year
	public static double Total(double array[]) {
		double total = 0;
		for(int i = 0; i < 12; ++i) {
			total = total + array[i];
		}
		total = total * 100;
		total = Math.round(total);
		total = total / 100;
		JOptionPane.showMessageDialog(null, "The total amount of rainfall this year was " + total + " inches.");
		return total;
	}
	//@param ttl, the total amount of rainfall during the year
	//@return the average number of inches of rain that fell that year
	public static double Average(double ttl) {
		double average = 0;
		average = ttl / 12;
		average = average * 100;
		average = Math.round(average);
		average = average / 100;

		JOptionPane.showMessageDialog(null, "The average amount of rainfall this year was " + average + " inches.");
		return average;
	}
	//@param array[], the amount of rain and month[], the month it rained te most
	public static void Highest(double array[], String month[]) {
		double highest = 0;
		int hp = 0; //hp stands for highest position
		for(int i = 0; i < 12; ++i) {
			if(highest < array[i]) {
				highest = array[i];
				hp = i;
			}
		}
		JOptionPane.showMessageDialog(null, "The month with the most amount of rainfall was " + month[hp] + " with " + highest + " inches of rain.");
	}
	//@param array[] the amount of rain and month[], the  month it rained the least
	public static void Lowest(double array[], String month[]) {
		double lowest = 0;
		for(int i = 0; i < 12; ++i) {
			lowest = array[0]; //just to set the lowest as the first element in the array
		}
		int lp = 0; //lp stands for lowest position
		for(int i = 0; i < 12; ++i) {
			if(lowest > array[i]) {
				lowest = array[i];
				lp = i;
			}
		}
		JOptionPane.showMessageDialog(null, "The month with the most amount of rainfall was " + month[lp] + " with " + lowest + " inches of rain.");
	}
}
